package com.kite.app.resources

import java.io.File
import java.security.SecureRandom

/**
 * Agent/依赖的环境文件声明。简单形式（纯路径字符串）保持必须预先存在；
 * 对象形式可带 autoGenerate 策略，目前支持 "random_token"：
 * 机器内部共享密钥（如 OpenClaw 网关 loopback 认证令牌）缺失时自动生成，
 * 不是用户凭据——真凭据文件仍走缺失报错与配置引导。
 */
data class KiteResourceEnvironmentFileSpec(
    val path: String,
    val autoGenerate: String? = null,
) {
    val requiresRandomToken: Boolean get() = autoGenerate == AUTO_GENERATE_RANDOM_TOKEN

    companion object {
        const val AUTO_GENERATE_RANDOM_TOKEN = "random_token"
    }
}

/** 环境文件的自动补齐与解析。只在启动链后台线程调用；幂等，存在即跳过。 */
internal object KiteResourceEnvironmentFileStore {
    private val random = SecureRandom()

    /**
     * 按 spec 补齐可自动生成的环境文件；返回纯路径表（名称→容器路径）供既有
     * 消费链使用。文件存在性在宿主侧检查（ContainerVisibleFileResolver 语义由
     * 调用方决定，这里直接对容器路径做宿主映射）。
     */
    fun ensureAutoGenerated(
        hostFileFor: (containerPath: String) -> File?,
        specs: Map<String, KiteResourceEnvironmentFileSpec>,
    ) {
        specs.values
            .filter(KiteResourceEnvironmentFileSpec::requiresRandomToken)
            .forEach { spec ->
                val hostFile = hostFileFor(spec.path) ?: return@forEach
                if (hostFile.isFile && hostFile.length() > 0L) return@forEach
                hostFile.parentFile?.mkdirs()
                val token = generateToken()
                runCatching {
                    hostFile.writeText(token)
                    // 私有权限：仅本应用可读（进程内无更强的 per-file 粒度）。
                    hostFile.setReadable(false, false)
                    hostFile.setReadable(true, true)
                    hostFile.setWritable(false, false)
                    hostFile.setWritable(true, true)
                }
            }
    }

    fun generateToken(): String {
        val bytes = ByteArray(32)
        random.nextBytes(bytes)
        return bytes.joinToString("") { "%02x".format(it) }
    }
}
