package com.kite.app.resources

import android.content.Context
import androidx.test.core.app.ApplicationProvider
import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

@RunWith(RobolectricTestRunner::class)
class KiteResourceEnvironmentFileTest {
    private val context: Context by lazy { ApplicationProvider.getApplicationContext() }
    private val loader by lazy { KiteResourceManifestLoader(context) }

    private fun resourceRoot(): File =
        sequenceOf(File("../assets/resources"), File("assets/resources"))
            .first(File::isDirectory)

    @Test
    fun `openclaw gateway token 声明为自动生成的机器令牌`() {
        val manifest = loader.parseManifestJson(
            File(resourceRoot(), "kite.openclaw/manifest.json").readText()
        )
        val profile = manifest.agentProfiles.single()
        val spec = profile.environmentFiles.getValue("OPENCLAW_GATEWAY_TOKEN")
        assertEquals("/workspace/.kf/secrets/kite.openclaw-gateway-token", spec.path)
        assertEquals("random_token", spec.autoGenerate)
        assertTrue(spec.requiresRandomToken)

        val dependency = profile.runtimeDependencies.single()
        assertEquals(
            spec,
            dependency.environmentFiles.getValue("OPENCLAW_GATEWAY_TOKEN"),
        )
    }

    @Test
    fun `纯字符串环境文件保持必须预先存在的语义`() {
        val manifest = loader.parseManifestJson(
            """
            {
              "schemaVersion": 1,
              "id": "kite.envfile-sample",
              "name": "EnvFile Sample",
              "display": {},
              "management": {"mode": "managed_extension"},
              "source": {"type": "npm", "package": "envfile-sample"},
              "agents": [{
                "id": "envfile-agent",
                "launch": {
                  "mode": "managed",
                  "providerId": "envfile",
                  "protocol": "acp",
                  "transport": "stdio",
                  "argv": ["node", "envfile-agent.mjs"],
                  "environmentFiles": {
                    "PLAIN_KEY": "/workspace/.kf/secrets/plain-value",
                    "TOKEN_KEY": {
                      "path": "/workspace/.kf/secrets/auto-token",
                      "autoGenerate": "random_token"
                    }
                  }
                }
              }]
            }
            """.trimIndent()
        )
        val specMap = manifest.agentProfiles.single().environmentFiles
        assertEquals("/workspace/.kf/secrets/plain-value", specMap.getValue("PLAIN_KEY").path)
        assertNull(specMap.getValue("PLAIN_KEY").autoGenerate)
        assertTrue(specMap.getValue("TOKEN_KEY").requiresRandomToken)
    }

    @Test
    fun `ensureAutoGenerated 幂等生成且不碰普通声明`() {
        val dir = context.cacheDir.resolve("env-file-test").apply { mkdirs() }
        val tokenFile = File(dir, "auto-token")
        tokenFile.delete()
        val plainFile = File(dir, "plain-value")
        plainFile.delete()
        val specs = mapOf(
            "TOKEN_KEY" to KiteResourceEnvironmentFileSpec(
                path = "/workspace/.kf/secrets/auto-token",
                autoGenerate = "random_token",
            ),
            "PLAIN_KEY" to KiteResourceEnvironmentFileSpec(
                path = "/workspace/.kf/secrets/plain-value",
            ),
        )
        val hostFileFor: (String) -> File? = { path ->
            File(dir, path.substringAfterLast('/'))
        }

        KiteResourceEnvironmentFileStore.ensureAutoGenerated(hostFileFor, specs)

        val first = tokenFile.readText()
        assertEquals(64, first.length)
        assertTrue(first.all { it in "0123456789abcdef" })
        // 普通声明缺失不生成
        assertTrue(!plainFile.exists())

        // 幂等：已存在不覆盖
        KiteResourceEnvironmentFileStore.ensureAutoGenerated(hostFileFor, specs)
        assertEquals(first, tokenFile.readText())
    }

    @Test
    fun `生成的令牌互不相同`() {
        assertNotEquals(
            KiteResourceEnvironmentFileStore.generateToken(),
            KiteResourceEnvironmentFileStore.generateToken(),
        )
    }
}
